import { db } from "./config/firebaseAdmin.js";

export const Posts = db.collection("posts");
export const Product = db.collection("products");
export const User = db.collection("users");
export const UserSessions = db.collection("usersessions");
export const Notification = db.collection("notifications");
//school related tables
export const Course = db.collection("courses");
export const Exceptions = db.collection("exceptions");
export const Assessment = db.collection("assessments");
export const TestSubmission = db.collection("testsubmission");
export const Attendance = db.collection("attendance");
export const Lectures = db.collection("lectures");
//school name is in lowercase, in frontend capitalize
export const OperationalInstitutions = db.collection("operationalinstitutions");
export const UserBankOrCardDetails = db.collection("usercardorbankdetails");
export const EmailVerification = db.collection("emailverify");
export const Follow = db.collection("follow");
export const Transactions = db.collection("transactions");
export const PaymentMethods = db.collection("paymentmethods");
export const ITag = db.collection("itags");
export const userPrefs = db.collection("userpreferences");
export const DeletedUser = db.collection("deletedusers");
export const PhoneNumberVerification = db.collection("phoneverify");
export const ProductOrder = db.collection("orders");
export const ProductImpression = db.collection("productimpressions");
export const ProductSales = db.collection("sales");
export const Reviews = db.collection("reviews");
export const Payout = db.collection("payout");
export const DropOffStation = db.collection("dropstations");
export const AccountStatement = db.collection("accountstatements");
export const SchoolConfiguration = db.collection("schoolconfiguration");
export const SupportTicket = db.collection("supporttickets");
export const Admin = db.collection("admins");
export const ControllerLog = db.collection("logs");
export const Comments = db.collection("postcomments");
export const PostReposters = db.collection("postreposters");
export const TaxEntries = db.collection("taxentries");
export const TaxStatements = db.collection("taxstatements");
export const Ads = db.collection("ads");
export const Message = db.collection("messages");